version: '3.8'

services:
  h2-database:
    image: oscarfonts/h2:latest
    container_name: h2-database
    ports:
      - "1521:1521"
      - "81:81"
    environment:
      H2_OPTIONS: -tcp -tcpAllowOthers -ifNotExists
    networks:
      - app-network

networks:
  app-network:
    driver: bridge